### ISSUE TITLE
Mercator projection at extreme latitudes

### ISSUE THREAD

**Issue by dgiesbrecht** [oculusinfo/aperture-tiles#105]
Geo located data at extreme latitudes, such as anomolous tweets at lat = 89 deg, can cause the mercator projection code to return negative y coords.

Proposed solution is to filter out these data points prior to binning (e.g., in RDDBinner and RDDLineBinner exclude any data points with lat > 80 or lat < -80).  We could also log the fact that these data points have been skipped.

**Comment by dgiesbrecht** [comment]
As suggested by Nathan, for the time being we can just modify RDDLineBinner (since this is more of a problem when binning line segments near the poles).  After conversion from lat/lon to tile/bin we can filter out any points that are outside the valid tile range for a given zoom level.

**Comment by cdbethune** [comment]
Fixed by #138
