### ISSUE TITLE
Renderers shouldn't request tiles directly

### ISSUE THREAD

**Issue by nkronenfeld** [oculusinfo/aperture-tiles#117]
Right now, on the server, the renderers are directly requesting and using tiles.

This causes a number of problems:
* It makes it much harder to cache tiles
* Courseness code needs to be worked into each renderer
* It just generally makes the renderers much more complex than they need to be.

The Tile Service should be requesting the tiles and passing them to the renderer.

**Comment by robharper** [comment]
I believe that the following method signature for renderers should be sufficient:
```java
private BufferedImage render(LayerConfiguration config, TileData<Double> data, BufferedImage bi)
```
which supports BufferedImage pooling if desired or simply:
```java
private BufferedImage render(LayerConfiguration config, TileData<Double> data)
```
which is sufficient if we want to make the buffered image pooling handled inside the renderer (may be the cleanest option).
