### ISSUE TITLE
Bad index values abort job in OnDemandAccumulatorPyramidIO

### ISSUE THREAD

**Issue by robharper** [oculusinfo/aperture-tiles#147]
```scala
val (x, y) = indexScheme.toCartesian(index)
```

Should be wrapped in a try/catch to handle cases where the index cannot be read/cast, e.g. nulls and other bad data.

**Comment by nkronenfeld** [comment]
Though there was a problem in the accumulator tiler, the problem Rob was seeing was actually in CSVReader - and would affect batch tiling as well as accumulator tiling.
