### ISSUE TITLE
Map and Layer files expect the pyramid with different labels

### ISSUE THREAD

**Issue by nkronenfeld** [oculusinfo/aperture-tiles#19]
The map configuration expects its pyramid configuration to be labelled "PyramidConfig.
The layer configuration expects its pyramid configuration to be labelled "pyramid".

The labels should be the same in both cases.

We should go through other similar cases and make sure we're consistent across the board.

**Comment by cdbethune** [comment]
I don't think this is relevant given the rework of the layers API - please verify.

**Comment by kbirk** [comment]
No longer relevant, all cases are under the attribute "pyramid".
