### ISSUE TITLE
Tile color rendering incorrectly maps mins/maxes when min bin is non-zero

### ISSUE THREAD

**Issue by robharper** [oculusinfo/aperture-tiles#71]
Specifically regarding [these two lines](https://github.com/oculusinfo/aperture-tiles/blob/develop/tile-service/src/main/java/com/oculusinfo/tile/rendering/impl/DoublesImageRenderer.java#L108-L109) in `DoublesImageRenderer`

If the min bin value is 0 the color ramp range is mapped correctly. If the min bin value is non-zero the min/max range against which values are transformed into colors is incorrect because it assumes a 0 minimum. The problem becomes more confusing (to the end user) if the rangeMin is set > 0. I believe the lines in question should read:

```java
double scaledLevelMinFreq = t.transform(minimumValue) + (t.transform(maximumValue)-t.transform(minimumValue))*rangeMin/100;
double scaledLevelMaxFreq = t.transform(minimumValue) + (t.transform(maximumValue)-t.transform(minimumValue))*rangeMax/100;
```

This is most apparent when bin values range into negative numbers.

**Comment by nkronenfeld** [comment]
I'm not understanding something here.

If I understand what you are doing here, you are implementing an unstated assumption that the transformers transform to [0, 1] into the renderer.

This wasn't the intent of the transformers - they are supposed to embody a comprehensible, simple mathematical transformation.

I would expect the fix to this problem to be just in the renderer, without having to touch the heart of the transformers (though perhaps it would require adding a getMinimumValue method to them)

**Comment by robharper** [comment]
My understanding is the gist of transformation is to map from input space to output space. Generally this means mapping from a numeric range [min,max] to a color ramp. [0,1] is a convenient generic output range that can be translated into any output (e.g. color ramp) with ease.

The existing linear transformer does map to a [0,1] output [here](https://github.com/oculusinfo/aperture-tiles/blob/develop/tile-service/src/main/java/com/oculusinfo/tile/rendering/transformations/value/LinearCappedValueTransformer.java#L40)

Also, this is derived from ApertureJS's concept of Range and Mapping constructs where Ranges map an arbitrary input set (numeric or otherwise) to an output set, generally [0,1].

**Comment by robharper** [comment]
Also, the log transformer is also mapping to [0,1] given an input in [1,supplied max].
