### ISSUE TITLE
Quick Start Guide needs updating

### ISSUE THREAD

**Issue by ryan-elliott** [oculusinfo/aperture-tiles#94]
The Quick Start Guide instructions for Client Configuration ( http://aperturetiles.com/docs/development/quickstart/#tile-client-configuration ) need to be updated.  For example, it references the crossplot-maps.json file under WEB-INF/classes/map which doesn't exist in the template.  The tile client template here http://aperturetiles.com/download/#tile-client-template also seems to have layers for both the julia set example and the twitter layer (the twitter layer should probably be removed), and the app.js file loads the world base map, not the extents of the julia set demo.

**Comment by mecrouch** [comment]
Cherry picked doc changes into 0.4.0-maintenance branch, and posted the updated Quick Start, Configuration and Download pages to aperturetiles.com along with the new Tile Quick Start Template ZIP download.
